const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.OVIE_PLAYWRIGHT_MODULE || 'playwright');
const root=path.resolve(__dirname,'../..');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file:///'+path.join(root,'ovie_commercial_workers_compensation_insights.html').replaceAll('\\','/'));
 await page.evaluate(()=>document.fonts.ready);
 assert.equal(await page.locator('#locationsList [data-location-entry]').count(),51);
 assert.equal(await page.locator('#classificationsList [data-class-entry]').count(),145);
 assert.equal(await page.locator('[data-class-group]').count(),39);
 assert.equal(await page.locator('#simplified-title').innerText(),'Your policy simplified');
 assert.equal(await page.locator('section[aria-labelledby="simplified-title"] [data-source]').count(),0);
 assert.equal(await page.getByText('Additional policy information',{exact:true}).count(),0);
 assert.equal(await page.locator('#classificationsList>summary .count-pill').innerText(),'39 states');
 assert.equal(await page.locator('#includedList .coverage-part').count(),2);
 assert.equal(await page.locator('#includedList>summary .count-pill').innerText(),'2 parts');
 const sources=await page.evaluate(()=>[...document.querySelectorAll('[data-source]')].every(b=>EVIDENCE[b.dataset.source]?.excerpt && EVIDENCE[b.dataset.source].page<=346));
 assert.ok(sources,'All sources resolve');
 for(const width of [320,390,456,1440]){
  await page.setViewportSize({width,height:844});
  const overflow=await page.evaluate(()=>document.getElementById('phone').scrollWidth>document.getElementById('phone').clientWidth);
  assert.equal(overflow,false,`No horizontal overflow at ${width}`);
  await page.screenshot({path:path.join(__dirname,`overview-${width}.png`)});
  const originalOpen=await page.locator('details').evaluateAll(els=>els.map(el=>el.open));
  await page.locator('details').evaluateAll(els=>els.forEach(el=>el.open=true));
  assert.equal(await page.locator('#phone').evaluate(el=>el.scrollWidth>el.clientWidth),false,`Expanded content fits at ${width}`);
  assert.ok(await page.locator('main [data-source]').evaluateAll(els=>els.filter(el=>el.getClientRects().length).every(el=>el.getBoundingClientRect().width>=44&&el.getBoundingClientRect().height>=44)),'Source targets at least 44px');
  await page.locator('details').evaluateAll((els,states)=>els.forEach((el,i)=>el.open=states[i]),originalOpen);
 }
 await page.setViewportSize({width:390,height:844});
 await page.locator('#employees-title').evaluate(el=>document.getElementById('phone').scrollTop=el.offsetTop-80);
 await page.screenshot({path:path.join(__dirname,'employees.png')});
 console.log(await page.locator('.class-preview').evaluateAll(els=>els.map(el=>({height:el.getBoundingClientRect().height,padding:getComputedStyle(el).padding,parent:el.parentElement.className}))));
 await page.evaluate(()=>document.getElementById('phone').scrollTop=0);
 const firstSource=page.locator('[data-source="cancel"]').first();
 await firstSource.click();
 await page.locator('#sourceSheet[open]').waitFor();
 assert.match(await page.locator('#sourceBody a').getAttribute('href'),/#page=340$/);
 await page.screenshot({path:path.join(__dirname,'source.png')});
 await page.keyboard.press('Escape');
 assert.equal(await firstSource.evaluate(el=>el===document.activeElement),true,'Source focus restored');
 await page.locator('[data-source="class27_8810"]').first().click();
 assert.match(await page.locator('.source-document-name').innerText(),/State payroll and premium schedule/);
 assert.match(await page.locator('.source-form').innerText(),/^Form reference: WC 99 00 01 C/);
 assert.ok((await page.locator('.source-field dd').allTextContents()).includes('$17,185,000'));
 await page.screenshot({path:path.join(__dirname,'readable-class-source.png')});
 await page.keyboard.press('Escape');
 await page.locator('[data-source="ratingExceptions"]').click();
 assert.equal(await page.locator('#sourceBody .source-record').count(),4);
 const pageLinks=await page.locator('#sourceBody .document-link').evaluateAll(els=>els.map(el=>el.getAttribute('href').split('#page=')[1]));
 assert.deepEqual(pageLinks,['29','43','56','62']);
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:1440,height:844});
 await page.locator('[data-source="class27_8810"]').first().click();
 const drawer=await page.locator('#sourceSheet').boundingBox();
 assert.ok(Math.abs(drawer.x+drawer.width-1440)<1&&drawer.y===0&&drawer.height===844,'Source is a right drawer on desktop');
 await page.screenshot({path:path.join(__dirname,'desktop-source-drawer.png')});
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:390,height:844});
 await page.locator('#includedList').evaluate(el=>document.getElementById('phone').scrollTop=el.offsetTop-80);
 await page.screenshot({path:path.join(__dirname,'included-hierarchy.png')});
 await page.locator('#locationsList>summary').click();
 await page.locator('#locationSearch').fill('MVP');
 assert.equal(await page.locator('#locationsList [data-location-entry]:visible').count(),2);
 await page.locator('#locationSearch').fill('unlikely-nonexistent');
 assert.match(await page.locator('#locationSearchStatus').innerText(),/No matching/);
 await page.locator('#locationSearch').fill('');
 await page.locator('#locationsList>summary').click();
 await page.locator('#classificationsList>summary').click();
 await page.locator('#classSearch').fill('California');
 assert.equal(await page.locator('#classificationsList [data-class-entry]:visible').count(),21);
 await page.locator('#classSearch').fill('8810');
 await page.screenshot({path:path.join(__dirname,'classes.png')});
 await page.locator('#classificationsList>summary').click();
 await page.locator('#premium-title').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(__dirname,'premium.png')});
 await page.evaluate(()=>{document.querySelector('.topbar').classList.remove('hidden-header');document.getElementById('phone').scrollTop=0});
 await page.locator('#searchButton').click();
 await page.locator('#insightsSearch').fill('8810');
 assert.ok(await page.locator('.search-result').count()>0);
 await page.locator('.search-result').last().click();
 assert.equal(await page.locator('#classificationsList').getAttribute('open'),'');
 await page.locator('#chatInput').click();
 assert.equal(await page.locator('#askOvieInput').evaluate(el=>el===document.activeElement),true);
 await page.locator('#askOvieInput').fill('Is harassment covered?');
 await page.keyboard.press('Enter');
 assert.match(await page.locator('#askOvieAnswer').innerText(),/EPLI is separate/);
 await page.locator('#closeAskOvie').click();
 await page.locator('[data-feedback="down"]').click();
 await page.locator('#feedbackForm button[type="submit"]').click();
 assert.match(await page.locator('#feedbackError').innerText(),/Select one reason/);
 await page.locator('input[name="reason"][value="other"]').check();
 await page.locator('#feedbackConcern').fill('Review the state schedule.');
 await page.locator('#feedbackForm button[type="submit"]').click();
 assert.equal(await page.locator('[data-feedback="down"]').getAttribute('aria-pressed'),'true');
 await page.locator('#watch-title').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(__dirname,'watchpoints.png')});
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(__dirname,'validation.json'),JSON.stringify({locations:51,classEntries:145,states:39,viewportWidths:[320,390,456,1440],sources:true,readableSourceTables:true,compositePageLinks:true,desktopSourceDrawer:true,expandedContentFits:true,sourceTargetSize:true,headingAndCountRoles:true,search:true,filters:true,sourceFocusRestoration:true,askOvie:true,feedbackValidation:true,pageErrors:errors},null,2));
 console.log('Passed: 51 locations, 145 classes, 39 states, source links, responsive widths, search, filters, focus restoration, Ask Ovie, feedback; no page errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
